#Expyriment 1.0.0 (Python 3.13.7), .xpe-file, coding: cp1252
#date: Wed Oct 08 2025 15:58:48
#sha1: ab4ee3
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='DESKTOP-GNBUSH4', release='11', version='10.0.26100', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
757,Stimulus,presented,0
758,Stimulus,presented,1
758,Stimulus,presented,2
759,Stimulus,presented,4
759,Stimulus,presented,5
760,Stimulus,presented,6
762,stderr,received,'Traceback (most recent call last):'
762,stderr,received,'  File "C:\\Users\\lucie\\Documents\\CogSup\\Programming\\Assignments\\Week-4\\Exercises\\ternus.py", line 44, in <module>\n    exp.clock.wait(ISI)\n                   ^^^'
762,stderr,received,"NameError: name 'ISI' is not defined"
